# Generated by Django 5.2.4 on 2025-07-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='avg_score',
            field=models.FloatField(default=0.0),
        ),
    ]
